name: 'Devploy - by DevGuys'
description: 'Deploy your project on a distant server using SSH or FTP protocol'
author: 'paul'
branding:
  icon: 'upload'
  color: 'green'
inputs:
  host:
    description: 'Hostname of the server'
    required: true
  username:
    description: 'username to use'
    required: true
  password:
    description: 'password to use'
    required: true
  port:
    description: 'port to use'
    default: 22
  source:
    description: 'local path'
    default: '/'
  target:
    description: 'remote target'
    default: '/home'
runs:
  using: 'node16'
  main: 'dist/index.js'